language: node_js

services:
  - docker

node_js:
  - "11"

before_install:
  - docker build -f Dockerfile_travis -t ammaorg/aquiladb:travis .
  - docker run -d -i -p 50051:50051 -t ammaorg/aquiladb:travis
  - docker ps -a
  - sudo apt-get install -y make
  - cd src

install:
  - npm install
  - cd test

script:
  - node test.js

branches:
  only:
  - develop